# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import services_pb2 as services__pb2


class UdaConnectServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createPerson = channel.unary_unary(
                '/UdaConnectService/createPerson',
                request_serializer=services__pb2.PersonMessage.SerializeToString,
                response_deserializer=services__pb2.Person.FromString,
                )
        self.createLocation = channel.unary_unary(
                '/UdaConnectService/createLocation',
                request_serializer=services__pb2.LocationMessage.SerializeToString,
                response_deserializer=services__pb2.Location.FromString,
                )


class UdaConnectServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createPerson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UdaConnectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createPerson': grpc.unary_unary_rpc_method_handler(
                    servicer.createPerson,
                    request_deserializer=services__pb2.PersonMessage.FromString,
                    response_serializer=services__pb2.Person.SerializeToString,
            ),
            'createLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.createLocation,
                    request_deserializer=services__pb2.LocationMessage.FromString,
                    response_serializer=services__pb2.Location.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UdaConnectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UdaConnectService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createPerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UdaConnectService/createPerson',
            services__pb2.PersonMessage.SerializeToString,
            services__pb2.Person.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UdaConnectService/createLocation',
            services__pb2.LocationMessage.SerializeToString,
            services__pb2.Location.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
