---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    name: kafka-consumer
    protocol: TCP
  selector:
    app: kafka
    id: "0"
  type: LoadBalancer
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka-consumer
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka-consumer
  template:
    metadata:
      labels:
        service: kafka-consumer
    spec:
      containers:
      - image: julianafogg/kafka-consumer:v1.0.0
        name: kafka-consumer
        ports:
          - containerPort: 9092
        imagePullPolicy: Always
      restartPolicy: Always
      
      