apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-consumer
  name: kafka-consumer
spec:
  ports:
  - name: "5000"
    port: 5000
  selector:
    service: kafka-consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka-consumer
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka-consumer
  template:
    metadata:
      labels:
        service: kafka-consumer
    spec:
      containers:
      - image: julianafogg/kafka_message_passing:latest
        name: kafka-consumer
        imagePullPolicy: Always
      restartPolicy: Always